pizzeria/pizzas/urls.py
""" Defines url patterns for pizzas"""

from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns =[
    # Homepage
    path('', views.index, name = 'index'),

    # Page that shows all pizzas.
    path('pizzas/', views.pizzas, name='pizzas'),
    ]

pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),

]

pizzeria/pizzas/models.py
from django.db import models
from django.db.models.fields import CharField, TextField

# Create your models here.

class Pizza(models.Model):

    """A Model of Pizza"""
    name = models.CharField(max_length = 200)

    def __str__(self):
        
        """ A String representation of Pizza model"""
        return self.name

class Topping(models.Model):

    """ A model of pizza toppings. """
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):

        """A String representation of topping model"""
        return self.name

pizzeria/pizzas/views.py
from django.shortcuts import render

from .models import Pizza

# Create your views here.
def index(request):
    
    """ The HomePage of pizzas."""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    # Show all pizzas.
    pizzas = Pizza.objects.order_by('id')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

pizzeria/pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">PizzaHouse</a> -

    <a href="{% url 'pizzas:pizzas' %}">PizzaHouse Pizzas</a>

</p>
{% block content %}{% endblock content %}

pizzeria/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}
{% block content %}
<p>PizzeriaHouse App</p>
<p>We are opening soon for 24/7 pizza delivery.</p>
{% endblock content %}

pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}
{% block content %}
 <p>Pizza</p>
<ul>
{% for pizza in pizzas %}
<li>{{ pizza }}</li>
{% empty %}
 <li>No pizza have been added yet.</li>
{% endfor %}
</ul>
{% endblock content %}